// <auto-generated />
using System;
using AsistenciaGR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsistenciaGR.Migrations
{
    [DbContext(typeof(AsistenciaGRContext))]
    [Migration("20260703033245_asgr3")]
    partial class asgr3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AsistenciaGR.Models.Asistencia", b =>
                {
                    b.Property<int>("AsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsId"));

                    b.Property<DateTime>("AsFecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AsJustificacion")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AsPorcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AsPresente")
                        .HasColumnType("bit");

                    b.Property<int?>("CaMaId")
                        .HasColumnType("int");

                    b.Property<int?>("MaId")
                        .HasColumnType("int");

                    b.Property<int?>("MateriasMaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioUsId")
                        .HasColumnType("int");

                    b.HasKey("AsId");

                    b.HasIndex("CaMaId");

                    b.HasIndex("MateriasMaId");

                    b.HasIndex("UsId");

                    b.HasIndex("UsuarioUsId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Carrera", b =>
                {
                    b.Property<int>("CaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaId"));

                    b.Property<string>("CaDenominacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MateriaMaId")
                        .HasColumnType("int");

                    b.HasKey("CaId");

                    b.HasIndex("MateriaMaId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("AsistenciaGR.Models.CarreraCohorte", b =>
                {
                    b.Property<int>("CaCoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaCoId"));

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int>("CoId")
                        .HasColumnType("int");

                    b.HasKey("CaCoId");

                    b.HasIndex("CaId");

                    b.HasIndex("CoId");

                    b.ToTable("CarreraCohorte");
                });

            modelBuilder.Entity("AsistenciaGR.Models.CarreraMateria", b =>
                {
                    b.Property<int>("CaMaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaMaId"));

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int>("MaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioUsId")
                        .HasColumnType("int");

                    b.HasKey("CaMaId");

                    b.HasIndex("CaId");

                    b.HasIndex("MaId");

                    b.HasIndex("UsuarioUsId");

                    b.ToTable("CarrerasMaterias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Cohorte", b =>
                {
                    b.Property<int>("CoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoId"));

                    b.Property<int>("CoAnio")
                        .HasColumnType("int");

                    b.Property<bool>("CoEstado")
                        .HasColumnType("bit");

                    b.HasKey("CoId");

                    b.ToTable("Cohorte");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Inscripciones", b =>
                {
                    b.Property<int>("InId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InId"));

                    b.Property<int>("CaMaId")
                        .HasColumnType("int");

                    b.Property<int?>("Carreras_MateriasCaMaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InFechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuariosUsId")
                        .HasColumnType("int");

                    b.HasKey("InId");

                    b.HasIndex("Carreras_MateriasCaMaId");

                    b.HasIndex("UsuariosUsId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Materia", b =>
                {
                    b.Property<int>("MaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaId"));

                    b.Property<int>("AsId")
                        .HasColumnType("int");

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int>("CaMaId")
                        .HasColumnType("int");

                    b.Property<int>("MaCantModulos")
                        .HasColumnType("int");

                    b.Property<string>("MaDenominacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MaModalidad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Rol", b =>
                {
                    b.Property<int>("RoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoId"));

                    b.Property<string>("RoDenominacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Usuario", b =>
                {
                    b.Property<int>("UsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsId"));

                    b.Property<int?>("CaCoId")
                        .HasColumnType("int");

                    b.Property<int>("RoId")
                        .HasColumnType("int");

                    b.Property<string>("UsApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsContrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsDni")
                        .HasColumnType("int");

                    b.Property<string>("UsEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsId");

                    b.HasIndex("CaCoId");

                    b.HasIndex("RoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Asistencia", b =>
                {
                    b.HasOne("AsistenciaGR.Models.CarreraMateria", "CarreraMateria")
                        .WithMany()
                        .HasForeignKey("CaMaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AsistenciaGR.Models.Materia", "Materias")
                        .WithMany("Asistencias")
                        .HasForeignKey("MateriasMaId");

                    b.HasOne("AsistenciaGR.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AsistenciaGR.Models.Usuario", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("UsuarioUsId");

                    b.Navigation("CarreraMateria");

                    b.Navigation("Materias");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Carrera", b =>
                {
                    b.HasOne("AsistenciaGR.Models.Materia", null)
                        .WithMany("Carreras")
                        .HasForeignKey("MateriaMaId");
                });

            modelBuilder.Entity("AsistenciaGR.Models.CarreraCohorte", b =>
                {
                    b.HasOne("AsistenciaGR.Models.Carrera", "Carrera")
                        .WithMany("CarreraCohortes")
                        .HasForeignKey("CaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistenciaGR.Models.Cohorte", "Cohorte")
                        .WithMany("CarreraCohortes")
                        .HasForeignKey("CoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Cohorte");
                });

            modelBuilder.Entity("AsistenciaGR.Models.CarreraMateria", b =>
                {
                    b.HasOne("AsistenciaGR.Models.Carrera", "Carrera")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("CaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistenciaGR.Models.Materia", "Materia")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("MaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistenciaGR.Models.Usuario", null)
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("UsuarioUsId");

                    b.Navigation("Carrera");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Inscripciones", b =>
                {
                    b.HasOne("AsistenciaGR.Models.CarreraMateria", "Carreras_Materias")
                        .WithMany()
                        .HasForeignKey("Carreras_MateriasCaMaId");

                    b.HasOne("AsistenciaGR.Models.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosUsId");

                    b.Navigation("Carreras_Materias");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Usuario", b =>
                {
                    b.HasOne("AsistenciaGR.Models.CarreraCohorte", "CarreraCohorte")
                        .WithMany()
                        .HasForeignKey("CaCoId");

                    b.HasOne("AsistenciaGR.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarreraCohorte");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Carrera", b =>
                {
                    b.Navigation("CarreraCohortes");

                    b.Navigation("CarreraMaterias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Cohorte", b =>
                {
                    b.Navigation("CarreraCohortes");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Materia", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("CarreraMaterias");

                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Usuario", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("CarreraMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
