// <auto-generated />
using System;
using AsistenciaGR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsistenciaGR.Migrations
{
    [DbContext(typeof(AsistenciaGRContext))]
    [Migration("20260525185314_asgr")]
    partial class asgr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AsistenciaGR.Models.Asistencia", b =>
                {
                    b.Property<int>("AsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsId"));

                    b.Property<DateTime?>("AsFecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AsJustificacion")
                        .HasColumnType("bit");

                    b.Property<bool>("AsPresente")
                        .HasColumnType("bit");

                    b.HasKey("AsId");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Carreras", b =>
                {
                    b.Property<int>("CaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaId"));

                    b.Property<string>("CaDenominacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Carreras_Materias", b =>
                {
                    b.Property<int>("CaMaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaMaId"));

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int?>("CarrerasCaId")
                        .HasColumnType("int");

                    b.Property<int>("MaId")
                        .HasColumnType("int");

                    b.Property<int?>("MateriasMaId")
                        .HasColumnType("int");

                    b.HasKey("CaMaId");

                    b.HasIndex("CarrerasCaId");

                    b.HasIndex("MateriasMaId");

                    b.ToTable("Carreras_Materias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Materias", b =>
                {
                    b.Property<int>("MaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaId"));

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int>("MaCantHoras")
                        .HasColumnType("int");

                    b.Property<string>("MaDenominacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaModalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Roles", b =>
                {
                    b.Property<int>("RoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoId"));

                    b.Property<string>("RoDenominacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Usuarios", b =>
                {
                    b.Property<int>("UsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsId"));

                    b.Property<int>("RoId")
                        .HasColumnType("int");

                    b.Property<int?>("RolesRoId")
                        .HasColumnType("int");

                    b.Property<string>("UsApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsDNI")
                        .HasColumnType("int");

                    b.Property<string>("UsNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsId");

                    b.HasIndex("RolesRoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Carreras_Materias", b =>
                {
                    b.HasOne("AsistenciaGR.Models.Carreras", "Carreras")
                        .WithMany("Carreras_Materias")
                        .HasForeignKey("CarrerasCaId");

                    b.HasOne("AsistenciaGR.Models.Materias", "Materias")
                        .WithMany("Carreras_Materias")
                        .HasForeignKey("MateriasMaId");

                    b.Navigation("Carreras");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Usuarios", b =>
                {
                    b.HasOne("AsistenciaGR.Models.Roles", "Roles")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolesRoId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Carreras", b =>
                {
                    b.Navigation("Carreras_Materias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Materias", b =>
                {
                    b.Navigation("Carreras_Materias");
                });

            modelBuilder.Entity("AsistenciaGR.Models.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
